export default {
    PRODUCT_MAP: {
        freshdesk: {
            productId: 1,
            productName: 'Freshdesk',
            url: 'https://freshdesk.com/signup?utm_source=Freshdesk%20App%20Gallery&amp;utm_medium=Install%20App%20Dialog%20box',
            productUrl: 'freshdesk.com',
            redirectUrl: '/a/admin/marketplace/gallery',
            galleryPagePath: '/a/admin/marketplace/gallery',
            isDeepLinkEnabled: true,
        },
        freshsales: {
            productId: 2,
            productName: 'Freshsales Classic',
            url: 'https://freshworks.com/freshsales-crm/signup',
            productUrl: 'freshsales.io',
            redirectUrl: '/settings/integrations/third-party-applications/view/all',
            galleryPagePath: '/settings/integrations/third-party-applications/view/all',
            isDeepLinkEnabled: true,
        },
        freshservice: {
            productId: 3,
            productName: 'Freshservice',
            url: 'https://freshservice.com/signup',
            productUrl: 'freshservice.com',
            redirectUrl: '/a/admin/marketplace/gallery',
            galleryPagePath: '/a/admin/marketplace/gallery',
            isDeepLinkEnabled: true,
        },
        freshchat: {
            productId: 4,
            productName: 'Freshdesk Messaging',
            url: 'https://www.freshworks.com/live-chat-software/',
            productUrl: 'web.freshchat.com/',
            redirectUrl: '/apps#',
            galleryPagePath: '/',
            isDeepLinkEnabled: false,
        },
        freshcaller: {
            productId: 5,
            productName: 'Freshdesk Contact Center',
            url: 'https://www.freshworks.com/freshcaller-cloud-pbx/signup/',
            productUrl: 'freshcaller.com',
            redirectUrl: '/mkp-gallery#',
            galleryPagePath: '/admin/mkp-gallery',
            isDeepLinkEnabled: false,
        },
        freshworks_crm: {
            productId: 8,
            productName: 'Freshsales Suite',
            url: 'https://www.freshworks.com/crm/signup/',
            productUrl: 'myfreshworks.com/crm/sales',
            redirectUrl: '/settings/integrations/third-party-applications/view/all',
            galleryPagePath: '/settings/integrations/third-party-applications/view/all',
            isDeepLinkEnabled: true,
        },
        freshteam: {
            productId: 6,
            productName: 'Freshteam',
            url: 'https://www.freshworks.com/hrms/signup/',
            productUrl: 'freshteam.com',
            redirectUrl: '/settings/apps',
            galleryPagePath: '/settings/apps',
            isDeepLinkEnabled: false,
        },
    },
    // todo: remove this feature flag if all the products are onboared
    // to agent view gallery
    AGENT_VIEW: {
        freshdesk: true,
        freshsales: false,
        freshservice: false,
        freshchat: false,
        freshcaller: false,
        freshworks_crm: false,
        freshteam: false,
    },
};
